### ISSUE TITLE
[BUG] curve-healthy-bot: not working

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1679]
the backend service needs to get swap route to exchange the token to settlement token on Curve and put it as swap_route params. Because we are missing the parameter, the backend script returns an error.

### Done when

- [x] curve-squeeze-leverage bot has been updated with the missing parameter
- [x] curve-healthy bot has been updated with the missing parameter

Some logs from service

```
Jun 10 18:36:56 bots-server start.sh[3654061]: CURVE-JS IS CONNECTED TO NETWORK: { name: 'MAINNET', chainId: 1 }
Jun 10 18:36:56 bots-server start.sh[3654061]: bot_info [
Jun 10 18:36:56 bots-server start.sh[3654061]:   {
Jun 10 18:36:56 bots-server start.sh[3654061]:     bot: '0x1BcCb8863E7aC10f9E048cCDAF7b5fca56D7076A',
Jun 10 18:36:56 bots-server start.sh[3654061]:     callbacker: '0xb911D7e59BA82FDF477a2Ab22Ff25125072C9282',
Jun 10 18:36:56 bots-server start.sh[3654061]:     callback_args: [ '0', '4924', '344782640' ]
Jun 10 18:36:56 bots-server start.sh[3654061]:   }
Jun 10 18:36:56 bots-server start.sh[3654061]: ]
Jun 10 18:36:56 bots-server start.sh[3654061]: createAndSignTx ERROR Error: Request failed with status code 500
Jun 10 18:36:56 bots-server start.sh[3654061]:     at createError (/home/rootedbox/app/curve-squeeze-leverage-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/createError.js:16:15)
Jun 10 18:36:56 bots-server start.sh[3654061]:     at settle (/home/rootedbox/app/curve-squeeze-leverage-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/settle.js:17:12)
Jun 10 18:36:56 bots-server start.sh[3654061]:     at IncomingMessage.handleStreamEnd (/home/rootedbox/app/curve-squeeze-leverage-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/adapters/http.js:322:11)
Jun 10 18:36:56 bots-server start.sh[3654061]:     at IncomingMessage.emit (node:events:525:35)
Jun 10 18:36:56 bots-server start.sh[3654061]:     at IncomingMessage.emit (node:domain:489:12)
Jun 10 18:36:56 bots-server start.sh[3654061]:     at endReadableNT (node:internal/streams/readable:1359:12)
```

```
Jun 10 18:36:56 bots-server start.sh[3654061]:     data: {
Jun 10 18:36:56 bots-server start.sh[3654061]:       code: 2,
Jun 10 18:36:56 bots-server start.sh[3654061]:       message: "failed to execute message; message index: 0: Error parsing into type curve_healthy_juice_bot_cw::msg::ExecuteMsg: missing field `swap_infos`: execute wasm contract failed [!cosm!wasm/wasmd@v0.50.0/x/wasm/keeper/keeper.go:404] with gas used: '97028'",
Jun 10 18:36:56 bots-server start.sh[3654061]:       details: []
Jun 10 18:36:56 bots-server start.sh[3654061]:     }
Jun 10 18:36:56 bots-server start.sh[3654061]:   },
```

**Comment by verabehr** [comment]
wc117 — Today at 2:56 PM
I found backend service needs to get swap route to exchange the token to settlement token on Curve and put it as swap_route params. Because we are missing the parameter, the backend script returns an error.

**Comment by ranshaojiqing** [comment]
@wc117 can you confirm this issue is fixed?

**Comment by verabehr** [comment]
@ranshaojiqing @wc117  (cc @fieldtheory123 )

did the following to confirm `curve-healthy-bot`

1. pull the latest code on the bot server in the `~/app/curve-healthy-bot` directory
2. restart service `sudo service curve-healthy-bot restart`
3. observe the logs `journalctl -u curve-healthy-bot -f`

I'm still seeing the same error - reopening

**Comment by verabehr** [comment]
For curve-squeeze-leverage the error message changed - new ticket opened here https://github.com/VolumeFi/paloma/issues/1682

**Comment by taariq** [comment]
@wc117 I don't see your comments on this ticket. We need your response here, ser. Also, please see: https://discord.com/channels/987730379182051408/1164263785956134992/1250201351145914530

**Comment by ranshaojiqing** [comment]
@taariq no immediate need for @wc117 's comments -- backend needs to supply the correct arg. in order for me to do that, i need to know what's really being asked here, because as far as i can tell i'm missing data i need.

agreed on https://discord.com/channels/987730379182051408/1164263785956134992/1250201351145914530 -- let's all discuss so i can get my bearings on what the ask is here

**Comment by verabehr** [comment]
marking as blocked until the smart contract bugs are fixed
